# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rahul Coutinho
email: rahuloc1809@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A website that includes professional experiences, new hobbies, fandoms and basically
  what I am up to in life. Created on 08/17/2019 so bear with me if this does not look
  like a finished product (in case you are on here too early :P)! Subscribe to blog RSS
  feeds if you are into those type of things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: crater1809
github_username:  rcoutin

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude: [vendor]  

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
